server/DentalClinic/Areas/Admin/Controllers/ReportController.cs
using DentalClinic.BL.Contracts;
using DentalClinic.BL.Models;
using DentalClinic.DB.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace DentalClinic.Areas.Admin.Controllers
{
    [Authorize]
    public class ReportController : AdminBaseController
    {
        //Dentist
        private readonly IReportService reportService;
        private readonly IDoctorService doctorService;
        private readonly UserManager<User> userManager;
        private readonly IErrorService errorService;


        public ReportController(
            IReportService _reportService,
            IDoctorService _doctorService,
            UserManager<User> _userManager,
            IErrorService _errorService)
        {
            reportService = _reportService;
            doctorService = _doctorService;
            userManager = _userManager;
            errorService = _errorService;
        }

        [HttpGet]
        public async Task<IActionResult> Dentists()
        {
            
            var result = await reportService.GetAllDentists();
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            string reportUserName = "";
            if (userId != null)
            {
                var user = await userManager.FindByIdAsync(userId);
                reportUserName = $"{user.FirstName} {user.LastName}";
            }
            ViewBag.reportUserName = reportUserName;
            ViewBag.Doctor = "All";
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> DentistSchedule()
        {
            
            var model = new DoctorScheduleViewModel()
            {
                Doctors = await doctorService.GetDoctorsAsync()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DentistSchedule(Guid DoctorId, DateTime startDate, DateTime endDate)
        {
            
            var result = await reportService.GetDentistScheduleByDate(DoctorId, startDate, endDate);
            var doctor = await doctorService.GetDoctorById(DoctorId);
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            string reportUserName = "";
            if (userId != null)
            {
                var user = await userManager.FindByIdAsync(userId);
                reportUserName = $"{user.FirstName} {user.LastName}";
            }
            ViewBag.reportUserName = reportUserName;
            ViewBag.Doctor = doctor.ElementAt(0).Name;
            ViewBag.startDate = startDate;
            ViewBag.endDate = endDate;
            return View("DentistScheduleResult", result);
        }

        [HttpGet]
        public async Task<IActionResult> DentistCustomer()
        {
            
            var model = new DoctorCustomerViewModel()
            {
                Doctors = await doctorService.GetDoctorsAsync()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DentistCustomer(DoctorCustomerViewModel model)
        {
            
            TimeSpan startTime = new TimeSpan(00, 00, 00);
            TimeSpan endTime = new TimeSpan(23, 59, 59);
            DateTime startDate = model.DateTimeSchedule + startTime;
            DateTime endDate = model.DateTimeSchedule + endTime;
            var result = await reportService.GetDoctorCustomerByDate(model.DoctorId, startDate, endDate);

            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            string reportUserName = "";
            if (userId != null)
            {
                var user = await userManager.FindByIdAsync(userId);
                reportUserName = $"{user.FirstName} {user.LastName}";
            }
            ViewBag.reportUserName = reportUserName;
            // ViewBag.Doctor = result.ElementAt(0).DoctorName;
            ViewBag.startDate = startDate;
            ViewBag.endDate = endDate;
            return View("DentistCustomerResult", result);
        }
    }
}

server/DentalClinic/Controllers/DentalServicesController.cs
using DentalClinic.BL.Contracts;
using DentalClinic.BL.Models;
using DentalClinic.BL.Service;
using DentalClinic.DB.Data.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace DentalClinic.Controllers
{
    public class DentalServicesController : Controller
    {
        private readonly IDentalService detnalServices;
        private readonly IErrorService errorService;
        public DentalServicesController(
            IDentalService _detnalServices,
            IErrorService _errorService
            )
        {
            detnalServices = _detnalServices;
            errorService = _errorService;
        }

        [HttpGet]
        public async Task<IActionResult> DentalServices()
        {
            var dentalServices = await detnalServices.GetAll();
            return View(dentalServices);
        }
    }
}

server/DentalClinic/Controllers/TeamController.cs
using DentalClinic.BL.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DentalClinic.Controllers
{
    public class TeamController : Controller
    {
        private readonly IDoctorService doctorService;
        private readonly IErrorService errorService;
        public TeamController(
            IDoctorService _doctorService,
            IErrorService _errorService
            )
        {
            doctorService = _doctorService;
            errorService = _errorService;
        }
        [HttpGet]
        public async Task<IActionResult> Team()
        {

            var doctors = await doctorService.GetAll();
            return View(doctors);
        }

        [HttpPost]
        public async Task<IActionResult> Team(Guid doctor, string doctorName)
        {
            string Title = $"Booked: {doctorName}";
            return RedirectToAction("Booked", "Booked", new { Title, doctor = doctor });
        }

    }
}

server/DentalClinic/Controllers/UsersController.cs
using DentalClinic.BL.Models;
using DentalClinic.DB.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using static DentalClinic.Areas.Admin.Constants.AdminConstants;

namespace DentalClinic.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {

        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly ILogger logger;

        public UsersController(
                                UserManager<User> _userManager,
                                SignInManager<User> _signInManager,
                                ILogger<HomeController> _logger)
        {
            userManager = _userManager;
            signInManager = _signInManager;
            logger = _logger;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {
            if (User.IsInRole(AdminRolleName))
            {
                return RedirectToAction("Index", "Admin", new { area = "Admin" });
            }

            var model = new UserViewModel();

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(UserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await userManager.FindByNameAsync(model.Email);

            if (user != null)
            {
                var result = await signInManager.PasswordSignInAsync(user, model.Password, false, false);
                
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            ModelState.AddModelError("", "Invalid login");

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Registration()
        {
            var model = new RegistrationViewModel();

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Registration(RegistrationViewModel model)
        {  

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = new User()
            {
                UserName = model.Email,
                FirstName = model.FirstName,
                LastName=model.LastName,
                Email = model.Email,
                PhoneNumber = model.Phonenumber,
                When = DateTime.Now,
                IsActive=1
            };

            var result = await userManager.CreateAsync(user, model.Password);
            

            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Login));
            }

            foreach (var item in result.Errors)
            {
                ModelState.AddModelError("", item.Description);
            }
            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

server/DentalClinic/Areas/Admin/Views/Shared/_Layout.cshtml
@{/*Admin page*/}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin</title>
    <link rel="icon" type="image/x-icon" src="http://res.cloudinary.com/ddfrnob2x/image/upload/v1670966541/diuzqrk4scauwwup2m5b.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a asp-area="" asp-controller="Home" asp-action="Index"><img class="navbar-brand" src="http://res.cloudinary.com/ddfrnob2x/image/upload/v1670966541/diuzqrk4scauwwup2m5b.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DentalServices" asp-action="DentalServices">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Team">Team</a>
                        </li>
                        @if (!User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Registration">Registration</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Administration</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Admin" asp-action="CreateDentist">Create dentist</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Admin" asp-action="CreateSchedule">Create schedule</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Reports</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Report" asp-action="Dentists">Dentists</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Report" asp-action="DentistSchedule">Dentist schedule</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Report" asp-action="DentistCustomer">Dentist customer</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Reception" asp-action="Reception">Reception</a>
                            </li>
                        }
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Dental Clinic </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/NavBarAdminPage.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>